# -*- coding: utf-8 -*-
"""Analitik Teks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7-_0eU2VGjKviRCRjlL1NovkuJLPIes
"""

import pandas as pd

df = pd.read_csv("GojekAppReviewV4.0.0-V4.9.3_Cleaned (1).csv")
df.head()

df.shape

df.isnull().sum()

df = df.dropna(subset=["content"])

def map_sentiment(score):
    if score <= 2:
        return "negative"
    elif score == 3:
        return "neutral"
    else:
        return "positive"

df["sentiment"] = df["score"].apply(map_sentiment)

df["sentiment"].value_counts()

import matplotlib.pyplot as plt

df["sentiment"].value_counts().plot(kind="bar")
plt.title("Distribusi Kelas Sentimen")
plt.xlabel("Sentiment")
plt.ylabel("Jumlah Data")
plt.show()

df = df[["content", "sentiment"]]
df.head()

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df["label"] = label_encoder.fit_transform(df["sentiment"])

label_encoder.classes_

from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    df,
    test_size=0.30,
    random_state=42,
    stratify=df["label"]
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=42,
    stratify=temp_df["label"]
)

len(train_df), len(val_df), len(test_df)

from transformers import AutoTokenizer

tokenizer_indobert = AutoTokenizer.from_pretrained(
    "indobenchmark/indobert-base-p1"
)

def tokenize_function(examples, tokenizer):
    return tokenizer(
        examples["content"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df)
val_dataset   = Dataset.from_pandas(val_df)
test_dataset  = Dataset.from_pandas(test_df)

train_indobert = train_dataset.map(
    lambda x: tokenize_function(x, tokenizer_indobert),
    batched=True
)

val_indobert = val_dataset.map(
    lambda x: tokenize_function(x, tokenizer_indobert),
    batched=True
)

test_indobert = test_dataset.map(
    lambda x: tokenize_function(x, tokenizer_indobert),
    batched=True
)

columns = ["input_ids", "attention_mask", "label"]

train_indobert.set_format(type="torch", columns=columns)
val_indobert.set_format(type="torch", columns=columns)
test_indobert.set_format(type="torch", columns=columns)

import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average="weighted"
    )
    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

def hp_space(trial):
    return {
        "learning_rate": trial.suggest_float(
            "learning_rate", 1e-5, 5e-5, log=True
        ),
        "per_device_train_batch_size": trial.suggest_categorical(
            "per_device_train_batch_size", [8, 16]
        ),
        "num_train_epochs": trial.suggest_int(
            "num_train_epochs", 2, 3
        ),
    }

training_args = TrainingArguments(
    output_dir="./results_random_search",
    eval_strategy="epoch",
    save_strategy="epoch",
    per_device_eval_batch_size=16,
    weight_decay=0.01,
    logging_dir="./logs",
    report_to="none",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
)

from transformers import AutoModelForSequenceClassification

def load_indobert_model():
    return AutoModelForSequenceClassification.from_pretrained(
        "indobenchmark/indobert-base-p1",
        num_labels=3
    )

from transformers import EarlyStoppingCallback

trainer_rs = Trainer(
    model_init=load_indobert_model,
    args=training_args,
    train_dataset=train_indobert,
    eval_dataset=val_indobert,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=1)],
)

best_run = trainer_rs.hyperparameter_search(
    direction="maximize",
    n_trials=1
)

final_training_args = TrainingArguments(
    output_dir="./results_final",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=best_run.hyperparameters["learning_rate"],
    per_device_train_batch_size=best_run.hyperparameters["per_device_train_batch_size"],
    per_device_eval_batch_size=16,
    num_train_epochs=best_run.hyperparameters["num_train_epochs"],
    weight_decay=0.01,
    report_to="none",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
)

from transformers import Trainer

final_trainer = Trainer(
    model=load_indobert_model(),
    args=final_training_args,
    train_dataset=train_indobert,
    eval_dataset=val_indobert,
    compute_metrics=compute_metrics
)

final_trainer.train()

final_test_results = final_trainer.evaluate(test_indobert)
final_test_results

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import numpy as np
import matplotlib.pyplot as plt

predictions = final_trainer.predict(test_indobert)

y_pred = np.argmax(predictions.predictions, axis=1)
y_true = predictions.label_ids

cm = confusion_matrix(y_true, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=label_encoder.classes_
)

disp.plot(cmap="Blues")
plt.title("Confusion Matrix IndoBERT (Final Model)")
plt.show()